# 通用的配置下沉到yml中，每台机器的特性配置放到docker启动文件
node.attr.zone: zone-default
node.attr.area: area-1

node.master: true
node.data: true
node.ingest: true

path.data: /usr/share/elasticsearch/data/data1,/usr/share/elasticsearch/data/data2
path.logs: /usr/share/elasticsearch/logs

network.host: 0.0.0.0
# network.publish_host: 10.102.0.74
# http.port: 9210

# discovery.zen.ping.unicast.hosts: ["10.102.0.73","10.102.0.74","10.102.0.75"]

#discovery.zen.minimum_master_nodes: 2
indices.breaker.total.limit: 70%

http.cors.enabled: true
http.cors.allow-origin: "*"

thread_pool.bulk.queue_size: 2000
thread_pool.search.queue_size: 2000