version: "3.1"

services:
  zookeeper:
    image: zookeeper:3.4
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    volumes:
      - "/data/zookeeper/data:/data"
      - "/data/zookeeper/datalog:/datalog"
      - "/data/zookeeper/log:/log"
    # 注意：如果改非standalone的集群部署模式，须外连访问其它服务，用Host网络
    # network_mode: "host"
    ports:
      - 2181:2181 #对client提供服务
      # - 2888:2888 #选举leader
      # - 3888:3888 #集群内部通讯
    environment:
      ZOO_MY_ID: 1
      ZOO_MAX_CLIENT_CNXNS: 1000
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 20
      ZOO_AUTOPURGE_PURGEINTERVAL: 48
      # 集群配置，当前仅部署单机
      #ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181