version: "3.1"

services:
  mqtt-broker:
    image: emqx/emqx:4.2.7
    restart: always
    hostname: mqttbroker
    # 注意：如果改非standalone的集群部署模式，须外连访问其它服务，用Host网络
    # network_mode: "host"
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083