version: '3.1'

services:
  portal:
    image: apolloconfig/apollo-portal:1.8.1
    restart: always
    hostname: apollo-portal
    container_name: apollo-portal
    volumes:
      - "/tmp/logs:/opt/logs"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8"
      APOLLO_PORTAL_ENVS: dev
      DEV_META: http://localhost:8080
    env_file: 
     - .secret/mysql.env
    # 通过宿主机访问数据库
    network_mode: "host"
    # ports: 
    #   - 8070:8070