version: "3.1"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    container_name: mysql
    volumes:
      - "/data/mysql/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file: 
      - .secret/mysql.env
    