version: '2'
services:
  kafka:
    #使用公版镜像
    image: wurstmeister/kafka:2.12-2.3.1
    restart: always
    # 通过宿主机访问ZK
    network_mode: host
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_HEAP_OPTS: -Xms128M -Xmx256M -XX:MetaspaceSize=196m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181