version: '3.1'

services:
  redis:
    image: redis:6.0
    restart: always
    hostname: redis
    container_name: redis
    volumes:
      - "/data/redis/data:/data"
    # 注意：如果改非standalone的集群部署模式，须外连访问其它服务，用Host网络
    # network_mode: "host"
    ports:
      - 6379:6379